/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 imperialDestroyer.gltf 
Author: Heataker (https://sketchfab.com/Heataker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-imperial-class-star-destroyer-fa18d537db4d4020a443c1802ec0f88e
Title: Star Wars; Imperial-Class Star Destroyer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/imperialDestroyer.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[154.328, 49.651, 459.356]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Emission2} />
      </group>
      <group position={[115.503, 85.403, -23.341]} rotation={[0.058, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_24.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Emission2} />
      </group>
      <group position={[183.986, 74.13, 218.505]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_43.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Emission2} />
      </group>
      <group position={[0, 156.259, 2.729]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Emission2} />
      </group>
      <group position={[115.105, 117.836, 363.243]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_60.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Emission2} />
      </group>
      <group position={[94.942, 139.527, -1.777]} rotation={[0.058, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_71.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Emission2} />
      </group>
      <group position={[179.637, 61.388, 256.384]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_74.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.Emission2} />
      </group>
      <group position={[228.156, 59.589, 69.335]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_77.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Emission2} />
      </group>
      <group position={[43.582, 104.643, -15.557]} rotation={[0.058, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_80.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.Emission2} />
      </group>
      <group position={[51.636, 63.064, 664.06]} rotation={[0.058, -1.309, 0]}>
        <mesh geometry={nodes.Object_127.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.Emission2} />
      </group>
      <group position={[120.439, 104.763, -22.677]} rotation={[0.058, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_142.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.Emission2} />
      </group>
      <group position={[115.014, 123.207, 166.8]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_165.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.Emission2} />
      </group>
      <group position={[231.233, 69.505, 103.278]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_196.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_197.geometry} material={materials.Emission2} />
      </group>
      <group position={[116.678, 107.182, 349.764]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_249.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_250.geometry} material={materials.Emission2} />
      </group>
      <group position={[110.774, 109.831, 398.194]} rotation={[0.058, 0, 0]}>
        <mesh geometry={nodes.Object_254.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_255.geometry} material={materials.Emission2} />
      </group>
      <group position={[-211.846, 0, -57.673]}>
        <mesh geometry={nodes.Object_277.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_278.geometry} material={materials.Emission1} />
      </group>
      <group position={[0, -5.253, 415.414]}>
        <mesh geometry={nodes.Object_284.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_285.geometry} material={materials.Emission2} />
      </group>
      <group position={[0, 251.668, 118.08]}>
        <mesh geometry={nodes.Object_292.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_293.geometry} material={materials.Emission2} />
        <mesh geometry={nodes.Object_294.geometry} material={materials.Emission1} />
      </group>
      <group position={[0, 0, 1400]}>
        <mesh geometry={nodes.Object_304.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_305.geometry} material={materials.Emission2} />
      </group>
      <group position={[108.707, 32.358, -44.394]}>
        <mesh geometry={nodes.Object_321.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_322.geometry} material={materials.Emission1} />
      </group>
      <group position={[435.753, 0, 21.628]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_326.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_327.geometry} material={materials.Emission2} />
      </group>
      <group position={[134.803, -1.889, 982.56]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_331.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.Emission2} />
      </group>
      <group position={[167.953, 4.726, 871.396]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_348.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_349.geometry} material={materials.Emission2} />
      </group>
      <group position={[337.43, 4.726, 312.694]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_367.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_368.geometry} material={materials.Emission2} />
      </group>
      <group position={[57.945, 4.768, 1262.54]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_370.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_371.geometry} material={materials.Emission2} />
      </group>
      <group position={[244.739, -0.978, 625.937]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_373.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_374.geometry} material={materials.Emission2} />
      </group>
      <group position={[382.664, -0.525, 174.976]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_376.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_377.geometry} material={materials.Emission2} />
      </group>
      <group position={[319.958, -1.316, 380.917]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_379.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_380.geometry} material={materials.Emission2} />
      </group>
      <group position={[113.868, 5.14, 1094.662]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_414.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_415.geometry} material={materials.Emission2} />
      </group>
      <group position={[388.608, -7.177, 156.385]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_471.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_472.geometry} material={materials.Emission2} />
      </group>
      <group position={[43.534, 6.314, 1320.109]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_476.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_477.geometry} material={materials.Emission2} />
      </group>
      <group position={[373.417, 6.821, 198.314]} rotation={[0, -0.288, 0]}>
        <mesh geometry={nodes.Object_519.geometry} material={materials.Regular} />
        <mesh geometry={nodes.Object_520.geometry} material={materials.Emission2} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Regular} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Emission2} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Regular} position={[55.03, 139.858, 0.264]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Regular} position={[181.878, 52.781, 347.904]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Regular} position={[228.969, 53.588, 63.718]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Regular} position={[113.096, 147.952, 103.205]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Regular} position={[179.806, 63.026, 244.917]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Regular} position={[38.183, 171.265, -5.556]} rotation={[1.629, 1.382, Math.PI]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Regular} position={[111.413, 137.533, 109.304]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Regular} position={[180.642, 63.657, 298.335]} rotation={[-3.084, 0, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Regular} position={[169.839, 97.76, 206.796]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Regular} position={[172.278, 81.897, 370.985]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Regular} position={[81.122, 147.014, 1.846]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Regular} position={[54.388, 107.186, -17.632]} rotation={[0.058, 0, Math.PI]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Regular} position={[182.506, 61.348, 150.814]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Regular} position={[183.886, 61.526, 168.227]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Regular} position={[34.959, 137.231, -19.053]} rotation={[0.058, 0, -1.751]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Regular} position={[200.21, 63.218, 14.525]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Regular} position={[145.563, 80.369, 485.891]} rotation={[0.058, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Regular} position={[113.075, 126.643, 47.067]} rotation={[0.058, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Regular} position={[180.624, 95.493, 28.844]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Regular} position={[0, 156.259, 2.729]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Regular} position={[90.039, 120.009, -18.343]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Regular} position={[56.199, 150.427, -2.558]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Regular} position={[57.814, 158.905, -2.521]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Regular} position={[36.271, 160.377, 1.519]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Regular} position={[112.008, 134.393, 34.925]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.Regular} position={[112.62, 136.668, 163.882]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.Regular} position={[182.886, 64.47, 161.567]} rotation={[0.058, 0, Math.PI]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Regular} position={[92.931, 107.69, 430.517]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Regular} position={[170.134, 95.51, 224.568]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.Regular} position={[149.36, 61.703, 432.961]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Regular} position={[153.696, 51.523, 498.078]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.Regular} position={[55.54, 89.945, 521.695]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials.Regular} position={[146.893, 87.474, 422.884]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.Regular} position={[149.871, 52.124, 507.927]} rotation={[0.058, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Object_103.geometry} material={materials.Regular} position={[137.148, 53.245, 519.858]} rotation={[0.058, -0.254, 0]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.Regular} position={[123.423, 75.391, 519.006]} rotation={[0.058, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.Regular} position={[180.881, 70.027, 182.783]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_109.geometry} material={materials.Regular} position={[180.194, 85.096, 158.371]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.Regular} position={[184.619, 66.466, 376.994]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.Regular} position={[180.624, 68.041, 298.812]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_115.geometry} material={materials.Regular} position={[183.714, 61.969, 324.67]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.Regular} position={[-74.122, 108.55, 487.955]} rotation={[0.058, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.Regular} position={[32.27, 92.404, 517.721]} rotation={[1.629, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.Regular} position={[104.705, 87.486, 522.368]} rotation={[0.058, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.Regular} position={[124.731, 53.942, 557.77]} rotation={[0.058, -0.254, 0]} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.Regular} position={[128.966, 64.975, 540.224]} rotation={[0.058, -0.254, 0]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Regular} position={[74.749, 54.45, 655.064]} rotation={[0.058, -1.309, 0]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Regular} position={[55.303, 73.87, 662.617]} rotation={[-0.56, -1.253, -0.594]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Regular} position={[96.172, 54.781, 649.333]} rotation={[0.058, -1.309, 0]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Regular} position={[12.518, 75.227, 673.711]} rotation={[0.058, -1.309, 0]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.Regular} position={[169.605, 101.83, 76.978]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.Regular} position={[171.912, 105.188, 110.638]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.Regular} position={[163.002, 96.561, -20.307]} rotation={[1.629, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials.Regular} position={[84.01, 109.671, -21.186]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_149.geometry} material={materials.Regular} position={[110.502, 118.323, 174.27]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_151.geometry} material={materials.Regular} position={[78.148, 97.543, -16.489]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_153.geometry} material={materials.Regular} position={[157.973, 72.158, -19.661]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_155.geometry} material={materials.Regular} position={[114.477, 123.637, 212.759]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_157.geometry} material={materials.Regular} position={[118.276, 116.37, 215.61]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_159.geometry} material={materials.Regular} position={[110.502, 118.323, 174.27]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.Regular} position={[113.391, 113.387, 256.443]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_163.geometry} material={materials.Regular} position={[113.451, 137.12, 173.033]} rotation={[1.629, 0, 0]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.Regular} position={[108.819, 138.337, 332.208]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.Regular} position={[208.374, 65.133, 145.315]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.Regular} position={[113.451, 138.201, 241.787]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.Regular} position={[98.27, 84.05, -23.034]} rotation={[1.629, 1.382, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Regular} position={[169.34, 102, 106.139]} rotation={[-3.084, 0, 0]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.Regular} position={[227.349, 72.454, 142.275]} rotation={[-1.513, 0, 0]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.Regular} position={[231.878, 70.25, 53.842]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.Regular} position={[152.025, 76.832, 410.157]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.Regular} position={[181.085, 66.61, 393.136]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.Regular} position={[113.06, 142.072, 235.048]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Regular} position={[182.32, 77.524, 223.486]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.Regular} position={[179.673, 79.712, 223.135]} rotation={[-1.513, 0, 0]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.Regular} position={[181.052, 86.567, 193.029]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.Regular} position={[112.008, 116.247, 336.654]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_199.geometry} material={materials.Regular} position={[227.112, 70.489, 116.647]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_201.geometry} material={materials.Regular} position={[231.862, 70.158, 72.351]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_203.geometry} material={materials.Regular} position={[193.238, 68.952, 142.49]} rotation={[1.629, 0, 0]} />
      <mesh geometry={nodes.Object_205.geometry} material={materials.Regular} position={[112.062, 125.565, 277.866]} rotation={[0.058, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_207.geometry} material={materials.Regular} position={[229.994, 56.128, 136.19]} rotation={[0.058, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_209.geometry} material={materials.Regular} position={[113.899, 120.815, 135.423]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_211.geometry} material={materials.Regular} position={[110.549, 129.822, 147.546]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_213.geometry} material={materials.Regular} position={[109.839, 145.337, 166.095]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_215.geometry} material={materials.Regular} position={[110.515, 143.173, 137.898]} rotation={[0.058, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Object_217.geometry} material={materials.Regular} position={[110.515, 144.041, 122.889]} rotation={[-3.084, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_219.geometry} material={materials.Regular} position={[108.746, 145.378, 84.942]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_221.geometry} material={materials.Regular} position={[112.674, 130.13, 140.688]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_223.geometry} material={materials.Regular} position={[168.724, 98.482, 136.737]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_225.geometry} material={materials.Regular} position={[91.212, 96.28, -22.551]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_227.geometry} material={materials.Regular} position={[116.331, 100.024, -19.262]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_229.geometry} material={materials.Regular} position={[139.556, 102.117, -18.53]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_231.geometry} material={materials.Regular} position={[107.462, 115.903, -16.225]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_233.geometry} material={materials.Regular} position={[100.188, 110.995, -17.327]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_235.geometry} material={materials.Regular} position={[135.195, 117.516, -19.147]} rotation={[-1.513, 0, 0]} />
      <mesh geometry={nodes.Object_237.geometry} material={materials.Regular} position={[113.294, 122.961, 294.685]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_239.geometry} material={materials.Regular} position={[180.444, 81.872, 18.612]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_241.geometry} material={materials.Regular} position={[193.461, 69.757, 17.251]} rotation={[0.058, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_243.geometry} material={materials.Regular} position={[228.333, 68.951, 38.802]} rotation={[0.058, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_245.geometry} material={materials.Regular} position={[112.231, 111.383, 378.16]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_247.geometry} material={materials.Regular} position={[112.712, 133.266, 342.053]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_252.geometry} material={materials.Regular} position={[108.55, 119.404, 289.436]} rotation={[-3.084, 0, 0]} />
      <mesh geometry={nodes.Object_257.geometry} material={materials.Regular} position={[104.584, 107.678, 402.361]} rotation={[0.058, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_259.geometry} material={materials.Regular} position={[108.881, 114.434, 383.905]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_261.geometry} material={materials.Regular} position={[92.891, 106.192, 467.475]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_263.geometry} material={materials.Regular} position={[89.742, 108.817, 455.654]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_265.geometry} material={materials.Regular} position={[88.56, 119.337, 444.605]} rotation={[-3.084, 0, 0]} />
      <mesh geometry={nodes.Object_267.geometry} material={materials.Regular} position={[44.592, 120.97, 490.12]} rotation={[0.058, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_269.geometry} material={materials.Regular} position={[168.451, 96.406, 244.509]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_271.geometry} material={materials.Regular} position={[11.663, 61.639, 690.51]} rotation={[0, 0, 0.201]} />
      <mesh geometry={nodes.Object_273.geometry} material={materials.Regular} position={[33.647, 296.004, 54.571]} rotation={[-0.596, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Object_275.geometry} material={materials.Regular} position={[104.746, 307.752, 85.434]} />
      <mesh geometry={nodes.Object_280.geometry} material={materials.Regular} />
      <mesh geometry={nodes.Object_282.geometry} material={materials.Regular} position={[0, 281.753, 82.581]} />
      <mesh geometry={nodes.Object_287.geometry} material={materials.Regular} />
      <mesh geometry={nodes.Object_289.geometry} material={materials.Regular} />
      <mesh geometry={nodes.Object_290.geometry} material={materials.Emission1} />
      <mesh geometry={nodes.Object_296.geometry} material={materials.Regular} position={[435.735, 0, 21.688]} rotation={[0.008, -0.251, -0.197]} />
      <mesh geometry={nodes.Object_298.geometry} material={materials.Regular} position={[82.11, -42.636, 708.05]} rotation={[-0.057, 0, 0.196]} />
      <mesh geometry={nodes.Object_300.geometry} material={materials.Regular} position={[0, 0, 39.99]} rotation={[-0.892, 0, 0]} />
      <mesh geometry={nodes.Object_302.geometry} material={materials.Regular} position={[0, 0, 1400]} />
      <mesh geometry={nodes.Object_307.geometry} material={materials.Regular} position={[213.748, 50.991, 183.57]} rotation={[0.058, 0, 0]} />
      <mesh geometry={nodes.Object_309.geometry} material={materials.Regular} position={[70.761, 276.111, 16.887]} rotation={[-1.186, 0.022, -0.157]} />
      <mesh geometry={nodes.Object_311.geometry} material={materials.Regular} position={[0, 281.753, 82.581]} />
      <mesh geometry={nodes.Object_313.geometry} material={materials.Regular} position={[213.748, 50.991, 183.57]} rotation={[0.058, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Object_315.geometry} material={materials.Regular} position={[0, 169.463, -63.11]} rotation={[0.253, 0, 0]} />
      <mesh geometry={nodes.Object_317.geometry} material={materials.Regular} position={[20.841, 158.192, -68.23]} rotation={[0.253, 0, 0.052]} />
      <mesh geometry={nodes.Object_319.geometry} material={materials.material_0} position={[0, 21.576, 734.276]} />
      <mesh geometry={nodes.Object_324.geometry} material={materials.HullPlating} />
      <mesh geometry={nodes.Object_329.geometry} material={materials.Regular} position={[147.243, -7.639, 931.378]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_334.geometry} material={materials.Regular} position={[180.906, -6.094, 821.474]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_336.geometry} material={materials.Regular} position={[121.385, -4.528, 1064.132]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_338.geometry} material={materials.Regular} position={[121.736, 1.853, 1024.529]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_340.geometry} material={materials.Regular} position={[129.482, 0.801, 999.403]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_342.geometry} material={materials.Regular} position={[127.412, 8.354, 995.164]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_344.geometry} material={materials.Regular} position={[138.988, -5.712, 967.162]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_346.geometry} material={materials.Regular} position={[156.765, 7.584, 898.973]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_351.geometry} material={materials.Regular} position={[174.818, 2.622, 852.081]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_353.geometry} material={materials.Regular} position={[116.124, -4.647, 1055.573]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_355.geometry} material={materials.Regular} position={[109.358, -4.598, 1116.138]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_357.geometry} material={materials.Regular} position={[133.184, -10.077, 1012.559]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_359.geometry} material={materials.Regular} position={[435.753, 0, 21.628]} rotation={[0, -0.288, -0.199]} />
      <mesh geometry={nodes.Object_361.geometry} material={materials.Regular} position={[232.688, -5.375, 687.501]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_363.geometry} material={materials.Regular} position={[136.576, 3.836, 968.458]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_365.geometry} material={materials.Regular} position={[160.719, 4.051, 889.237]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_382.geometry} material={materials.Regular} position={[88.214, -3.5, 1166.184]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_384.geometry} material={materials.Regular} position={[264.838, -4.477, 564.028]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_386.geometry} material={materials.Regular} position={[280.402, -6.094, 485.582]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_388.geometry} material={materials.Regular} position={[164.285, -10.643, 893.076]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_390.geometry} material={materials.Regular} position={[50.257, 3.836, 1279.567]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_392.geometry} material={materials.Regular} position={[302.384, 2.191, 451.862]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_394.geometry} material={materials.Regular} position={[370.742, 1.218, 226.062]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_396.geometry} material={materials.Regular} position={[28.585, 0.124, 1359.464]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_398.geometry} material={materials.Regular} position={[249.911, -6.402, 610.763]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_400.geometry} material={materials.Regular} position={[291.505, -5.247, 471.3]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_402.geometry} material={materials.Regular} position={[52.582, -5.322, 1294.704]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_404.geometry} material={materials.Regular} position={[37.234, 6.28, 1329.029]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_406.geometry} material={materials.Regular} position={[306.671, 7.048, 410.517]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_408.geometry} material={materials.Regular} position={[360.078, 6.592, 232.77]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_410.geometry} material={materials.Regular} position={[249.16, -7.64, 636.17]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_412.geometry} material={materials.Regular} position={[303.574, -6.393, 452.564]} rotation={[Math.PI / 2, 0, 0.288]} scale={1.5} />
      <mesh geometry={nodes.Object_417.geometry} material={materials.Regular} position={[291.448, 8.385, 440.817]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_419.geometry} material={materials.Regular} position={[246.684, 3.838, 586.977]} rotation={[0, -0.288, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_421.geometry} material={materials.Regular} position={[85.887, -8.444, 1172.45]} rotation={[0, -0.288, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_423.geometry} material={materials.Regular} position={[237.56, -3.261, 665.065]} rotation={[0, -0.288, Math.PI / 2]} />
      <mesh geometry={nodes.Object_425.geometry} material={materials.Regular} position={[243.31, 0.2, 640.41]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_427.geometry} material={materials.Regular} position={[242.462, 7.278, 640.159]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_429.geometry} material={materials.Regular} position={[245.987, 9.177, 642.688]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_431.geometry} material={materials.Regular} position={[249.666, 2.1, 614.75]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_433.geometry} material={materials.Regular} position={[246.527, 7.584, 593.747]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_435.geometry} material={materials.Regular} position={[286.816, -1.386, 495.342]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_437.geometry} material={materials.Regular} position={[274.482, 8.357, 531.122]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_439.geometry} material={materials.Regular} position={[275.655, 0.728, 494.619]} rotation={[0, -0.288, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_441.geometry} material={materials.Regular} position={[26.99, 2.725, 1377.212]} rotation={[-Math.PI, 0.288, 0]} />
      <mesh geometry={nodes.Object_443.geometry} material={materials.Regular} position={[30.963, -6.919, 1339.122]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_445.geometry} material={materials.Regular} position={[16.607, -5.292, 1402.632]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_447.geometry} material={materials.Regular} position={[54.239, -6.494, 1273.434]} rotation={[0, -0.288, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_449.geometry} material={materials.Regular} position={[11.311, 7.568, 1446.952]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_451.geometry} material={materials.Regular} position={[7.918, 6.976, 1412.328]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_453.geometry} material={materials.Regular} position={[7.194, -6.492, 1448.05]} />
      <mesh geometry={nodes.Object_455.geometry} material={materials.Regular} position={[259.225, -11.102, 569.518]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_457.geometry} material={materials.Regular} position={[282.307, -6.437, 494.385]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_459.geometry} material={materials.Regular} position={[302.655, -8.651, 433.46]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_461.geometry} material={materials.Regular} position={[294.57, 4.652, 437.451]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_463.geometry} material={materials.Regular} position={[298.928, 0.605, 437.995]} rotation={[0, -0.288, Math.PI / 2]} />
      <mesh geometry={nodes.Object_465.geometry} material={materials.Regular} position={[299.611, 10.107, 421.357]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_467.geometry} material={materials.Regular} position={[60.328, 1.853, 1234.609]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_469.geometry} material={materials.Regular} position={[322.652, -5.319, 350.09]} rotation={[-Math.PI, 0.288, 0]} />
      <mesh geometry={nodes.Object_474.geometry} material={materials.Regular} position={[26.941, -7.807, 1369.222]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_479.geometry} material={materials.Regular} position={[28.428, 7.955, 1345.091]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_481.geometry} material={materials.Regular} position={[83.581, 2.249, 1156.315]} rotation={[0, -0.288, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_483.geometry} material={materials.Regular} position={[341.967, -0.416, 291.101]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_485.geometry} material={materials.Regular} position={[410.925, 1.06, 57.717]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_487.geometry} material={materials.Regular} position={[424.041, -8.751, 35.256]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_489.geometry} material={materials.Regular} position={[373.253, -5.157, 184.758]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_491.geometry} material={materials.Regular} position={[387.813, -0.665, 141.431]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_493.geometry} material={materials.Regular} position={[382.958, 14.221, 15.534]} rotation={[-Math.PI / 2, 0, -0.288]} />
      <mesh geometry={nodes.Object_495.geometry} material={materials.Regular} position={[415.448, -7.493, 54.439]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_497.geometry} material={materials.Regular} position={[412.614, -0.331, 39.064]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_499.geometry} material={materials.Regular} position={[416.215, 9.489, 45.32]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_501.geometry} material={materials.Regular} position={[382.853, 3.541, 23.238]} rotation={[0, 1.283, 0]} />
      <mesh geometry={nodes.Object_503.geometry} material={materials.Regular} position={[388.775, 11.403, 19.128]} rotation={[0, 1.283, Math.PI / 2]} scale={1.5} />
      <mesh geometry={nodes.Object_505.geometry} material={materials.Regular} position={[407.516, 5.849, 86.64]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_507.geometry} material={materials.Regular} position={[401.375, -7.331, 101.59]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_509.geometry} material={materials.Regular} position={[380.443, 9.515, 151.058]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_511.geometry} material={materials.Regular} position={[330.973, 4.764, 334.334]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_513.geometry} material={materials.Regular} position={[326.621, -2.217, 328.456]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_515.geometry} material={materials.Regular} position={[311.439, 5.46, 388.758]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_517.geometry} material={materials.Regular} position={[369.537, -3.677, 180.522]} rotation={[Math.PI / 2, 0, 0.288]} scale={1.5} />
      <mesh geometry={nodes.Object_522.geometry} material={materials.Regular} position={[370.737, 7.011, 213.671]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_524.geometry} material={materials.Regular} position={[382.173, -6.804, 165.245]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_526.geometry} material={materials.Regular} position={[400.799, 2.238, 92.447]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_528.geometry} material={materials.Regular} position={[394.519, 9.448, 118.355]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_530.geometry} material={materials.Regular} position={[398.806, 8.983, 112.838]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_532.geometry} material={materials.Regular} position={[409.204, -7.331, 88.256]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_534.geometry} material={materials.Regular} position={[76.523, 5.849, 1204.055]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_536.geometry} material={materials.Regular} position={[64.889, -4.68, 1212.591]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_538.geometry} material={materials.Regular} position={[100.266, 4.54, 1144.297]} rotation={[-Math.PI, 0.288, 0]} />
      <mesh geometry={nodes.Object_540.geometry} material={materials.Regular} position={[79.156, 9.34, 1183.46]} rotation={[0, -0.288, 0]} />
      <mesh geometry={nodes.Object_542.geometry} material={materials.Regular} position={[75.135, 6.655, 1197.542]} rotation={[0, -0.288, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/imperialDestroyer.gltf')
