/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 starDestroyer.gltf 
Author: DanielBeltranSantiago (https://sketchfab.com/DanielBeltranSantiago)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-destroyer-e7424b1644554fd8b741a5470c28bb5e
Title: Star Destroyer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/starDestroyer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.White_Color} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.White_Color} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Top_Bump} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Grey} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Blue_Emission} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Edge_Bump_Alt} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Top_Bump_Alt} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.White_Color} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.White_Color} />
    </group>
  )
}

useGLTF.preload('/starDestroyer.gltf')
