/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tie.gltf 
Author: Daniel (https://sketchfab.com/DanielAndersson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-tiein-interceptor-80171ec2930b4949836bcf24d9694c41
Title: Star Wars: TIE/in Interceptor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tie(props) {
  const { nodes, materials } = useGLTF('/tie.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
        <group position={[0, 0.136, 0]}>
          <mesh geometry={nodes.Engines_0.geometry} material={materials.ScratchedMetal} />
          <mesh geometry={nodes.Engines_1.geometry} material={materials.RedEngineGlow} />
        </group>
        <group position={[0, 0.11, 0.067]}>
          <mesh geometry={nodes.Window_0.geometry} material={materials.ReflectiveGlass} />
          <mesh geometry={nodes.Window_1.geometry} material={materials.ScratchedMetalDark} />
        </group>
        <mesh geometry={nodes.ArmGreebles_0.geometry} material={materials.ScratchedMetal} scale={0.082} />
        <mesh geometry={nodes.ArmPlates_0.geometry} material={materials.ScratchedMetal} />
        <mesh geometry={nodes.Arms_0.geometry} material={materials.ScratchedMetal} />
        <mesh geometry={nodes.Arms_1.geometry} material={materials.ScratchedMetalDark} />
        <mesh geometry={nodes.CockpitGreebles_0.geometry} material={materials.ScratchedMetal} position={[0, 0.11, 0.067]} />
        <mesh geometry={nodes.EngineGreebles_0.geometry} material={materials.ScratchedMetal} position={[0, 0.136, 0]} />
        <mesh geometry={nodes.HullPlates_0.geometry} material={materials.ScratchedMetal} />
        <mesh geometry={nodes.MainHull_0.geometry} material={materials.ScratchedMetal} />
        <mesh geometry={nodes.MainHull_1.geometry} material={materials.ReflectiveGlass} />
        <mesh geometry={nodes.MainHull_2.geometry} material={materials.ScratchedMetalDark} />
        <mesh geometry={nodes.Wings_0.geometry} material={materials.ScratchedMetal} />
        <mesh geometry={nodes.Wings_1.geometry} material={materials.TieWingMesh} />
        <mesh geometry={nodes.Wings_2.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/tie.gltf')
